spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/fantan?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 'root'
      # 配置初始化大小、最小、最大
      max-active: 10
      initial-size: 2
      min-idle: 2
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '/druid/*'
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true

mybatis-plus:
  type-aliases-package: com.dashuai.learning.mybatis.freemarker.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
